name: ${project.name}
main: net.daboross.bukkitdev.skywars.SkyWarsPlugin
version: ${project.version}
authors: [Dabo Ross, ImSrPanda]
description: ${project.description}
url: ${project.url}
softdepend: [Vault, WorldEdit, MultiInv]
commands:
  skywars:
    aliases: [rsw]
  skywarssetup:
    aliases: [rsws]
